/* TriARge — Einsatzszenario "Halle (Saale), Kröllwitz — Hochwasser".
 *
 * Frei erfundene Übungslage auf echtem Kartenmaterial. Alle Personendaten sind
 * simuliert, ebenso Pegelstände, Einsatzmittel und Funkverkehr. Ortsangaben
 * (Kröllwitz, Saaleaue, Peißnitz, Klinikum Kröllwitz) sind real, die Lage ist
 * es nicht.
 *
 * Charakter der Lage: kein Schlagartig-Ereignis wie ein Einsturz, sondern eine
 * über Stunden wachsende Fläche — Deichverteidigung, Evakuierung aus dem
 * Rückstau, Wasserrettung. Die Patienten kommen verteilt und über einen langen
 * Zeitraum; mehrere Abschnitte entstehen erst im Verlauf.
 */

"use strict";

window.SZENARIEN = window.SZENARIEN || [];

window.SZENARIEN.push((function () {
  // Kritische Stelle: unterspülter Uferabschnitt am Fuß der Talstraße.
  const EPI = [51.50560, 11.94620];

  const abschnitte = [
    {
      id: "DEICH", kurz: "DEICHV.", name: "Deichverteidigung Uferweg West",
      ll: EPI, r: 150, art: "einsatz",
      info: "Sandsackverbau auf 400 m Länge, Quellkade an zwei Stellen. Kontrollgänge im 20-Minuten-Takt.",
      leitung: "EA 1 — Deichverteidigung (THW OV Halle, ZTr)",
    },
    {
      id: "EVAK", kurz: "EVAK SÜD", name: "Evakuierungsabschnitt Kröllwitz Süd",
      ll: [51.50420, 11.94700], r: 170, art: "einsatz",
      info: "58 Haushalte in der Uferzone. Räumung von Erdgeschoss und Keller, Tierrettung über EA 5.",
      leitung: "EA 2 — Evakuierung (BF Halle, B-Dienst)",
    },
    {
      id: "WR", kurz: "BOOTE", name: "Bootseinsatzstelle Talstraße",
      ll: [51.50510, 11.94380], r: 70, art: "transport",
      info: "Slipstelle am Fuß der Talstraße. Zwei Mehrzweckboote, ein Rettungsboot DLRG, Sprechfunk auf Kanal Wasser.",
      leitung: "EA 3 — Wasserrettung (DLRG Bezirk Halle)",
    },
    {
      id: "PA", kurz: "PA 1", name: "Patientenablage Talstraße",
      ll: [51.50680, 11.94280], r: 60, art: "med",
      info: "Hochwasserfrei über der Talstraße, kurze Wege zu Deichlinie, Evakuierung und Bootsstelle. Übernahme und Sichtung durch den LNA.",
      leitung: "EA 4 — Med / Patientenablage (OrgL Wendt)",
      kapazitaet: 20,
    },
    {
      id: "PA2", kurz: "PA 2", name: "Patientenablage Klinikumszufahrt",
      ll: [51.50260, 11.94120], r: 55, art: "med",
      t: 1080,
      info: "Ablage für die Verlegung aus den Pflegeeinrichtungen. Übergabe direkt an die KTW-Kette.",
      leitung: "EA 8 — Verlegung",
      kapazitaet: 15,
      funk: "Patientenablage 2 an der Klinikumszufahrt steht. Übergabe der Verlegungspatienten direkt an die KTW-Kette.",
    },
    {
      id: "BHP", kurz: "BHP 25", name: "Behandlungsplatz Turnhalle Heideallee",
      ll: [51.50960, 11.93900], r: 80, art: "med",
      info: "Turnhalle an der Heideallee. Beheizt, Wärmeerhalt und Aufwärmzone für Unterkühlte, 25 Plätze.",
      leitung: "EA 4 — Behandlung (LNA Dr. Seifert)",
      kapazitaet: 25,
    },
    {
      id: "RMHP", kurz: "RMHP", name: "Rettungsmittel-Halteplatz Heideallee",
      ll: [51.51030, 11.93760], r: 45, art: "transport",
      info: "Abtransport ab Behandlungsplatz. Anfahrt Dölauer Straße, Abfahrt Richtung Klinikum und Innenstadt.",
      leitung: "EA 6 — Transport (OrgL Krause)",
    },
    {
      id: "BR", kurz: "BR", name: "Bereitstellungsraum Nord",
      ll: [51.51300, 11.93220], r: 90, art: "transport",
      info: "Sammelraum für nachrückende Kräfte und Fahrzeuge, Führung über EA 6. Verpflegung ab 08:00.",
      leitung: "EA 6 — Transport",
    },
    {
      id: "BST", kurz: "BST", name: "Betreuungsstelle / Notunterkunft",
      ll: [51.51100, 11.93000], r: 90, art: "betreuung",
      info: "Grundschule Kröllwitz. Registrierung, Feldbetten für 180 Personen, PSNV, Tiersammelstelle im Nebenhof.",
      leitung: "EA 5 — Betreuung (DRK KV Halle)",
      kapazitaet: 180,
    },
    {
      id: "EL", kurz: "ELW 2", name: "Technische Einsatzleitung",
      ll: [51.50790, 11.94010], r: 45, art: "fuehrung",
      info: "ELW 2 an der Kreuzung Heideallee/Talstraße. Stab S1–S4, Verbindung zum Krisenstab der Stadt.",
      leitung: "ÖEL Radtke (BF Halle), UG-ÖEL",
      hq: true,
    },
    {
      id: "SAND", kurz: "SANDSACK", name: "Sandsack-Füllstelle und Logistik",
      ll: [51.51180, 11.93800], r: 70, art: "sonstig",
      t: 240,
      info: "Füllstelle mit Radlader, 9.000 Sandsäcke im Umlauf. Transport zur Deichlinie über Kirchbergweg.",
      leitung: "EA 7 — Logistik (THW FGr Log)",
      funk: "Füllstelle Kirchbergweg läuft. Zwei Radlader, Nachschub Sand über Dölauer Straße. Erste Kette zum Uferweg steht.",
    },
    {
      id: "EVAK2", kurz: "EVAK KLINIK", name: "Evakuierungsabschnitt Klinikumszufahrt",
      ll: [51.50190, 11.94020], r: 130, art: "einsatz",
      t: 1080,
      info: "Zufahrt Ernst-Grube-Straße droht zu überspülen. Vorsorgliche Verlegung von 14 immobilen Patienten aus zwei Pflegeeinrichtungen.",
      leitung: "EA 8 — Verlegung (OrgL Wendt)",
      funk: "Abschnitt Klinikumszufahrt eingerichtet. Verlegung von 14 immobilen Patienten aus zwei Pflegeeinrichtungen läuft an, KTW-Kontingent angefordert.",
    },
    {
      id: "VER", kurz: "ABL. VERST.", name: "Ablage Verstorbene",
      ll: [51.51000, 11.94020], r: 30, art: "sonstig",
      t: 1500,
      info: "Sichtgeschützt am Kirchbergweg. Freigabe durch Polizei, Personalien über Betreuungsstelle.",
      leitung: "Polizeirevier Halle Nord",
    },
  ];

  const gefahren = [
    {
      id: "G1", code: "PEGEL", art: "wasser", stufe: 3,
      name: "Saale — Pegel über Meldestufe 4",
      ll: [51.50600, 11.94800], r: 0,
      t: 0,
      status: "steigend",
      verantwortlich: "Hochwasserzentrale / Krisenstab der Stadt",
      info: "Pegel Halle-Trotha steigt weiter. Scheitel für den Vormittag erwartet. Deichverteidigung auf 400 m Länge, Kontrollgänge im 20-Minuten-Takt.",
      messwert: {
        label: "Pegel Halle-Trotha", wert: 712, einheit: "cm", warn: 700, trend: 1,
        spanne: [640, 790], rate: 0.05, rauschen: 0.4,
        // Scheitel gegen Minute 15 der Übung, danach fällt der Pegel langsam.
        wendeT: 900, wendeTrend: -0.4, wendeStatus: "Scheitel erreicht, langsam fallend",
        wendeText: "Pegel Halle-Trotha: Scheitel erreicht — Wert fällt langsam",
        wendeFunk: "Hochwasserzentrale meldet Scheitel. Pegel fällt langsam, Deichlinie bleibt besetzt.",
      },
    },
    {
      id: "G2", code: "UNTER", art: "einsturz", stufe: 3,
      name: "Deichunterspülung Uferweg West",
      ll: EPI, r: 90,
      t: 0,
      status: "laufend",
      verantwortlich: "THW OV Halle (Fachberater Deich) / EA 1",
      info: "Quellkade auf 30 m Länge, austretendes Wasser führt Sand. Auflastfilter im Bau, Kontrolle alle 10 Minuten. Kein Aufenthalt landseitig am Deichfuß.",
    },
    {
      id: "G3", code: "TREIB", art: "wasser", stufe: 2,
      name: "Treibgut / Verklausung Kröllwitzer Brücke",
      ll: [51.50560, 11.94880], r: 70,
      t: 120,
      status: "laufend",
      verantwortlich: "Wasserstraßenamt / EA 3",
      info: "Stämme und Gartenmobiliar stauen sich am mittleren Pfeiler. Bootsverkehr flussab der Brücke gesperrt, Räumung nur bei Tageslicht.",
    },
    {
      id: "G4", code: "STROM", art: "strom", stufe: 2,
      name: "Netzabschaltung Uferzone",
      ll: [51.50480, 11.94660], r: 260,
      t: 300,
      status: "laufend",
      verantwortlich: "Netzbetreiber / EA 2",
      info: "Ortsnetzstation am Zollrain vorsorglich freigeschaltet. Rund 340 Haushalte ohne Strom, zwei Heimbeatmungs- und ein Dialysepatient bekannt — Vorrang bei der Evakuierung.",
    },
    {
      id: "G5", code: "ÖL", art: "gas", stufe: 2,
      name: "Heizöl aus aufgeschwommenem Tank",
      ll: [51.50440, 11.94760], r: 110,
      t: 660,
      status: "laufend",
      verantwortlich: "Umweltamt / FW Halle Gefahrgut",
      info: "Kellertank aufgeschwommen und abgerissen. Ölfilm auf dem Rückstauwasser, Ölsperre gesetzt. Kein Betreten überfluteter Keller, Zündquellen vermeiden.",
      messwert: {
        label: "Ölfilm-Ausdehnung", wert: 60, einheit: "m", warn: 80, trend: 1,
        spanne: [0, 200], rate: 0.04, rauschen: 0.3,
        wendeT: 1200, wendeTrend: -0.6, wendeStatus: "Ölsperre wirkt, Ausdehnung rückläufig",
        wendeText: "Ölsperre geschlossen — Ausdehnung rückläufig",
        endeUnter: 15, endeText: "Ölaustritt eingedämmt", endeVon: "FW Halle Gefahrgut",
        endeFunk: "Ölsperre hält, Ausdehnung unter 15 m. Ölschadenbeseitigung übernimmt Fachfirma.",
      },
    },
    {
      id: "G6", code: "ABBR", art: "einsturz", stufe: 3,
      name: "Böschungsabbruch Uferweg Süd",
      ll: [51.50340, 11.94760], r: 60,
      t: 1020,
      status: "laufend",
      verantwortlich: "EA 1 / Fachberater THW",
      info: "Auf 25 m Länge ist die Böschung abgerutscht, ein Uferweg-Abschnitt ist weg. Bereich gesperrt, Kräfte zurückgenommen, Aufklärung über Drohne.",
    },
    {
      id: "G7", code: "TRINK", art: "wasser", stufe: 1,
      name: "Trinkwasser — Rückstau in der Kanalisation",
      ll: [51.50700, 11.94290], r: 200,
      t: 1320,
      status: "beobachtet",
      verantwortlich: "Stadtwerke / Gesundheitsamt",
      info: "Abwasserrückstau in tiefliegenden Kellern. Abkochgebot für die Uferzone vorbereitet, Kontakt mit verschmutztem Wasser meiden.",
    },
    {
      id: "G8", code: "MENGE", art: "menge", stufe: 1,
      name: "Schaulustige auf der Kröllwitzer Brücke",
      ll: [51.50540, 11.94880], r: 60,
      t: 1620,
      status: "beobachtet",
      verantwortlich: "Polizeirevier Halle Nord",
      info: "Rund 80 Personen auf dem Brückenbauwerk, Belastung und Sicht der Bootsführer beeinträchtigt. Räumung der Gehwege veranlasst.",
    },
  ];

  const sperren = [
    { id: "S1", name: "Kröllwitzer Brücke — Sperrung für den Verkehr", ll: [51.50570, 11.94720], von: "Polizei Halle 21/1" },
    { id: "S2", name: "Talstraße unterhalb Kirchbergweg", ll: [51.50660, 11.94080], von: "FW Halle 12/1" },
    { id: "S3", name: "Am Zollrain / Uferzone", ll: [51.50480, 11.94690], von: "Polizei Halle 21/2" },
    { id: "S4", name: "Heideallee / Forsterstraße", ll: [51.50960, 11.93620], von: "Ordnungsamt" },
    { id: "S5", name: "Ernst-Grube-Straße — Zufahrt Klinikum", ll: [51.50280, 11.94120], von: "Polizei Halle 21/3" },
  ];

  const poi = [
    { name: "Universitätsklinikum Halle (Kröllwitz)", ll: [51.50130, 11.93960], art: "medizin" },
    { name: "Kröllwitzer Brücke", ll: [51.50560, 11.94880], art: "amt" },
    { name: "Grundschule Kröllwitz (Notunterkunft)", ll: [51.51100, 11.93000], art: "schule" },
    { name: "Turnhalle Heideallee (BHP)", ll: [51.50960, 11.93900], art: "amt" },
    { name: "Peißnitzinsel (überflutet)", ll: [51.50320, 11.95040], art: "gruen" },
    { name: "Bootshaus / Slipstelle", ll: [51.50510, 11.94380], art: "amt" },
    { name: "Ortsnetzstation Am Zollrain (frei)", ll: [51.50480, 11.94660], art: "amt" },
    { name: "Pflegeheim Saaleblick", ll: [51.50260, 11.94320], art: "medizin" },
  ];

  const kliniken = [
    { id: "K1", name: "Universitätsklinikum Halle (Saale)", ll: [51.50130, 11.93960], km: 1.4, minuten: 6,
      stufe: "Maximalversorgung / ÜRZ", schockraum: 3, kinder: true, neuro: true, frei: { SK1: 3, SK2: 6, SK3: 10 } },
    { id: "K2", name: "BG Klinikum Bergmannstrost Halle", ll: [51.46560, 11.96900], km: 6.8, minuten: 14,
      stufe: "Schwerbrandverletzte / Querschnitt", schockraum: 2, kinder: false, neuro: true, frei: { SK1: 2, SK2: 4, SK3: 5 } },
    { id: "K3", name: "Krankenhaus St. Elisabeth und St. Barbara", ll: [51.48420, 11.96940], km: 5.1, minuten: 12,
      stufe: "Schwerpunktversorgung", schockraum: 1, kinder: false, neuro: false, frei: { SK1: 1, SK2: 5, SK3: 9 } },
    { id: "K4", name: "Krankenhaus Martha-Maria Halle-Dölau", ll: [51.50290, 11.87960], km: 5.6, minuten: 13,
      stufe: "Regelversorgung", schockraum: 1, kinder: false, neuro: false, frei: { SK1: 1, SK2: 4, SK3: 8 } },
    { id: "K5", name: "Universitätsklinikum Leipzig (RTH)", ll: [51.33170, 12.38460], km: 38.0, minuten: 18,
      stufe: "Maximalversorgung / ÜRZ", schockraum: 3, kinder: true, neuro: true, frei: { SK1: 2, SK2: 3, SK3: 4 } },
  ];

  const mittel = [
    { id: "ELW2", name: "ELW 2 Halle", kurz: "EL", art: "fuehrung", basis: "EL", rolle: "Technische Einsatzleitung", besatzung: 6 },
    { id: "HLF1", name: "Florian Halle 1/46", kurz: "HLF", art: "loesch", basis: "EVAK", rolle: "Menschenrettung, Türöffnung, Lenzarbeiten", besatzung: 9 },
    { id: "HLF2", name: "Florian Halle 3/46", kurz: "HL2", art: "loesch", basis: "DEICH", rolle: "Deichverteidigung, Beleuchtung", besatzung: 9 },
    { id: "THW1", name: "THW Halle — Zugtrupp", kurz: "TH1", art: "loesch", basis: "DEICH", rolle: "Fachberatung Deich, Auflastfilter", besatzung: 6 },
    { id: "THW2", name: "THW Halle — FGr Wassergefahren", kurz: "TH2", art: "trupp", basis: "WR", rolle: "Bootsbetrieb, Menschenrettung aus dem Wasser", besatzung: 6 },
    { id: "BOOT1", name: "Mehrzweckboot Halle 1", kurz: "B1", art: "trupp", basis: "WR", rolle: "Evakuierung über Wasser", besatzung: 4 },
    { id: "BOOT2", name: "Rettungsboot DLRG Halle", kurz: "B2", art: "trupp", basis: "WR", rolle: "Wasserrettung, Uferabsuche", besatzung: 4 },
    { id: "T1", name: "Rettungstrupp 1", kurz: "T1", art: "trupp", basis: "EVAK", rolle: "Räumung Erdgeschosse, Sichtung", besatzung: 2 },
    { id: "T2", name: "Rettungstrupp 2", kurz: "T2", art: "trupp", basis: "EVAK", rolle: "Räumung Erdgeschosse, Sichtung", besatzung: 2 },
    { id: "T5", name: "Rettungstrupp 3", kurz: "T5", art: "trupp", basis: "DEICH", rolle: "Deichlinie, Erstversorgung", besatzung: 2 },
    { id: "T6", name: "Rettungstrupp 4", kurz: "T6", art: "trupp", basis: "EVAK", rolle: "Räumung Erdgeschosse, Sichtung", besatzung: 2 },
    { id: "T3", name: "Trag-Trupp SEG 1", kurz: "T3", art: "trupp", basis: "PA", rolle: "Ablage → Behandlungsplatz", besatzung: 4 },
    { id: "T4", name: "Trag-Trupp SEG 2", kurz: "T4", art: "trupp", basis: "PA", rolle: "Ablage → Behandlungsplatz", besatzung: 4 },
    { id: "GWS", name: "GW-San Halle", kurz: "GS", art: "loesch", basis: "BHP", rolle: "Material Behandlungsplatz 25", besatzung: 3 },
    { id: "LNA", name: "LNA Dr. Seifert", kurz: "LN", art: "arzt", basis: "PA", rolle: "Leitender Notarzt, Sichtung", besatzung: 2 },
    { id: "NEF1", name: "NEF Halle 1", kurz: "N1", art: "nef", basis: "PA", rolle: "Notarzt, erweiterte Maßnahmen", besatzung: 2 },
    { id: "RTW1", name: "RTW Halle 1/83-1", kurz: "R1", art: "rtw", basis: "BR", rolle: "Transport", besatzung: 2 },
    { id: "RTW2", name: "RTW Halle 1/83-2", kurz: "R2", art: "rtw", basis: "BR", rolle: "Transport", besatzung: 2 },
    { id: "RTW3", name: "RTW Halle 4/83-1", kurz: "R3", art: "rtw", basis: "BR", rolle: "Transport", besatzung: 2 },
    { id: "RTW4", name: "RTW Saalekreis 8/83-1", kurz: "R4", art: "rtw", basis: "BR", rolle: "Transport", besatzung: 2 },
    { id: "KTW1", name: "KTW SEG Halle 1", kurz: "K1", art: "rtw", basis: "BR", rolle: "Verlegung immobiler Patienten", besatzung: 2 },
    { id: "RTH1", name: "Christoph 84", kurz: "H1", art: "rth", basis: "BHP", rolle: "Luftrettung, Ferntransport", besatzung: 3 },
    { id: "POL1", name: "Polizei Halle 21/1", kurz: "P1", art: "polizei", basis: "S1", rolle: "Absperrung Brücke", besatzung: 2 },
    { id: "POL2", name: "Polizei Halle 21/2", kurz: "P2", art: "polizei", basis: "S3", rolle: "Absperrung Uferzone", besatzung: 2 },
    { id: "DRN1", name: "Drohne EA Aufklärung", kurz: "DR", art: "drohne", basis: "DEICH", rolle: "Deichkontrolle, Wärmebild", besatzung: 1 },
  ];

  /* Patientenroster — bei einer Hochwasserlage kommen die Betroffenen über
   * Stunden verteilt: Unterkühlung, internistische Zwischenfälle unter der
   * Evakuierung, Verletzungen bei der Deichverteidigung. */
  const patienten = [
    { id: 1, t: 20, ll: [51.50480, 11.94690], kat: "SK2", sex: "m", alter: 68, geh: false, wach: true, atemweg: true,
      vit: { af: 22, puls: 104, spo2: 93, rrs: 148, rrd: 88, gcs: 15, temp: 34.6 },
      verletzt: ["Unterkühlung 34,6 °C", "Prellung Hüfte"], massnahmen: ["Wärmeerhalt", "Sauerstoff"],
      trupp: "T1", befund: "Männlich, 68, aus dem Keller im Rückstauwasser geborgen. Zittern, verlangsamt, 34,6 °C — gelb, Wärmeerhalt." },
    { id: 2, t: 58, ll: [51.50440, 11.94720], kat: "SK1", sex: "w", alter: 79, geh: false, wach: false, atemweg: true,
      vit: { af: 26, puls: 118, spo2: 88, rrs: 96, gcs: 10, temp: 32.8 },
      verletzt: ["schwere Unterkühlung 32,8 °C", "Exsikkose"], massnahmen: ["Wärmeerhalt", "Sauerstoff", "Volumen warm"],
      trupp: "T2", befund: "Weiblich, 79, im ungeheizten Obergeschoss aufgefunden, 32,8 °C, GCS 10 — rot, aktive Erwärmung." },
    { id: 3, t: 96, ll: [51.50520, 11.94420], kat: "SK3", sex: "m", alter: 34, geh: true, wach: true, atemweg: true,
      vit: { af: 16, puls: 88, spo2: 98, gcs: 15 },
      verletzt: ["Schnittwunde Fuß (Treibgut)"], massnahmen: ["Verband", "Tetanusstatus offen"],
      trupp: "T1", befund: "Männlich, 34, Anwohner, Schnittwunde am Fuß im Wasser — grün, Tetanusschutz klären." },
    { id: 4, t: 142, ll: [51.50580, 11.94600], kat: "SK2", sex: "m", alter: 51, geh: false, wach: true, atemweg: true,
      vit: { af: 20, puls: 112, spo2: 96, rrs: 158, rrd: 94, gcs: 15 },
      verletzt: ["LWS-Distorsion", "Muskelzerrung"], massnahmen: ["Analgesie", "Lagerung"],
      trupp: "T1", befund: "Helfer, 51, beim Sandsackverbau umgeknickt, starke Rückenschmerzen — gelb." },
    { id: 5, t: 190, ll: [51.50400, 11.94660], kat: "SK1", sex: "m", alter: 74, geh: false, wach: true, atemweg: true,
      vit: { af: 24, puls: 128, spo2: 89, rrs: 104, rrd: 62, gcs: 14 },
      verletzt: ["kardiale Dekompensation", "bekannte Herzinsuffizienz"], massnahmen: ["Oberkörper hoch", "Sauerstoff", "Monitoring"],
      trupp: "T2", befund: "Männlich, 74, Atemnot unter der Evakuierung, feuchte RGs beidseits — rot, NEF nachgefordert." },
    { id: 6, t: 236, ll: [51.50460, 11.94800], kat: "SK3", sex: "w", alter: 29, geh: true, wach: true, atemweg: true,
      vit: { af: 18, puls: 92, spo2: 99, gcs: 15 },
      verletzt: ["akute Belastungsreaktion"], massnahmen: ["Betreuung"],
      trupp: "T2", befund: "Weiblich, 29, Wohnung unter Wasser, weint, keine Verletzung — grün, PSNV." },
    { id: 7, t: 288, ll: [51.50360, 11.94740], kat: "SK2", sex: "w", alter: 63, geh: false, wach: true, atemweg: true,
      vit: { af: 19, puls: 96, spo2: 95, rrs: 142, gcs: 15 },
      verletzt: ["Dialysepatientin — Termin ausgefallen"], massnahmen: ["Monitoring", "Nephrologie voranmelden"],
      trupp: "T1", befund: "Weiblich, 63, Dialyse heute ausgefallen, Ödeme zunehmend — gelb, Uniklinikum voranmelden." },
    { id: 8, t: 340, ll: [51.50500, 11.94560], kat: "SK2", sex: "m", alter: 44, geh: false, wach: true, atemweg: true,
      vit: { af: 21, puls: 106, spo2: 94, rrs: 136, gcs: 15 },
      verletzt: ["Quetschung Hand", "offene Wunde"], massnahmen: ["Verband", "Analgesie", "Schienung"],
      trupp: "T1", befund: "THW-Helfer, 44, Hand zwischen Bohle und Ladung — gelb, Handchirurgie." },
    { id: 9, t: 396, ll: [51.50420, 11.94860], kat: "SK1", sex: "m", alter: 22, geh: false, wach: false, atemweg: false,
      vit: { af: 8, puls: 132, spo2: 76, gcs: 5, temp: 31.9 },
      verletzt: ["Beinaheertrinken", "schwere Unterkühlung 31,9 °C"], massnahmen: ["Beatmung", "Wärmeerhalt", "Absaugbereitschaft"],
      trupp: "THW2", befund: "Männlich, 22, aus der Strömung geborgen, Beinaheertrinken, 31,9 °C, GCS 5 — rot, ECMO-Zentrum voranmelden.",
      verschlechtert: { t: 620, kat: "SK1", vit: { puls: 148, spo2: 71, gcs: 3 },
        massnahmen: ["Beatmung", "Katecholamine", "Wärmeerhalt", "ECMO-Zentrum angemeldet"],
        befund: "Kreislauf instabil, Sättigung fällt weiter — Ferntransport per RTH in Vorbereitung." } },
    { id: 10, t: 452, ll: [51.50260, 11.94820], kat: "SK3", sex: "w", alter: 55, geh: true, wach: true, atemweg: true,
      vit: { af: 17, puls: 86, spo2: 98, gcs: 15 },
      verletzt: ["Hautkontakt mit Abwasser"], massnahmen: ["Reinigung", "Impfstatus klären"],
      trupp: "T2", befund: "Weiblich, 55, längerer Kontakt mit Rückstauwasser, Hautreizung — grün, Impfstatus prüfen." },
    { id: 11, t: 512, ll: [51.50540, 11.94480], kat: "SK2", sex: "m", alter: 39, geh: false, wach: true, atemweg: true,
      vit: { af: 23, puls: 114, spo2: 92, rrs: 128, gcs: 15 },
      verletzt: ["Sprunggelenksfraktur V. a.", "Unterkühlung 35,4 °C"], massnahmen: ["Schienung", "Wärmeerhalt", "Analgesie"],
      trupp: "T1", befund: "Männlich, 39, im Wasser gestürzt, Sprunggelenk deformiert — gelb." },
    { id: 12, t: 580, ll: [51.50340, 11.94700], kat: "TOT", sex: "m", alter: 81, geh: false, wach: false, atemweg: false,
      vit: {}, verletzt: ["keine Lebenszeichen"], massnahmen: [],
      trupp: "T2", befund: "Männlich, 81, im überfluteten Erdgeschoss aufgefunden, sichere Todeszeichen — schwarz." },
    { id: 13, t: 650, ll: [51.50480, 11.94380], kat: "SK3", sex: "m", alter: 16, geh: true, wach: true, atemweg: true,
      vit: { af: 18, puls: 94, spo2: 99, gcs: 15 },
      verletzt: ["Unterkühlung leicht 35,8 °C"], massnahmen: ["Trockene Kleidung", "warme Getränke"],
      trupp: "THW2", befund: "Jugendlicher, 16, mit dem Boot vom Uferweg geholt, durchnässt — grün, Aufwärmzone." },
    { id: 14, t: 716, ll: [51.50300, 11.94420], kat: "SK1", sex: "w", alter: 86, geh: false, wach: true, atemweg: true,
      vit: { af: 25, puls: 122, spo2: 87, rrs: 92, gcs: 13, temp: 34.1 },
      verletzt: ["Pneumonie V. a.", "Unterkühlung", "Immobilität"], massnahmen: ["Sauerstoff", "Wärmeerhalt", "Antibiose erwogen"],
      trupp: "T3", befund: "Weiblich, 86, aus Pflegeheim Saaleblick, fiebrig, Sättigung 87 % — rot, Klinikum voranmelden." },
    { id: 15, t: 790, ll: [51.50560, 11.94720], kat: "SK2", sex: "m", alter: 47, geh: false, wach: true, atemweg: true,
      vit: { af: 20, puls: 100, spo2: 95, rrs: 144, gcs: 15 },
      verletzt: ["Augenreizung (Heizöl)", "Übelkeit"], massnahmen: ["Augenspülung", "Frischluft"],
      trupp: "T1", befund: "Männlich, 47, Kontakt mit Ölfilm beim Sichern des Tanks — gelb, Augenspülung läuft." },
    { id: 16, t: 866, ll: [51.50420, 11.94560], kat: "SK3", sex: "w", alter: 71, geh: true, wach: true, atemweg: true,
      vit: { af: 17, puls: 90, spo2: 97, rrs: 162, gcs: 15 },
      verletzt: ["hypertone Entgleisung", "Aufregung"], massnahmen: ["Monitoring", "Ruhe"],
      trupp: "T2", befund: "Weiblich, 71, RR 180/100 nach Räumung der Wohnung — grün, ärztliche Kontrolle BHP." },
    { id: 17, t: 944, ll: [51.50380, 11.94880], kat: "SK2", sex: "m", alter: 58, geh: false, wach: true, atemweg: true,
      vit: { af: 22, puls: 108, spo2: 93, rrs: 132, gcs: 14 },
      verletzt: ["Aspiration Saalewasser", "Unterkühlung 34,9 °C"], massnahmen: ["Sauerstoff", "Wärmeerhalt", "Monitoring"],
      trupp: "BOOT2", befund: "Männlich, 58, vom gekenterten Kanu geborgen, hustet, hat Wasser aspiriert — gelb, engmaschig." },
    { id: 18, t: 1024, ll: [51.50220, 11.94180], kat: "SK2", sex: "w", alter: 90, geh: false, wach: true, atemweg: true,
      vit: { af: 19, puls: 98, spo2: 94, rrs: 128, gcs: 14 },
      verletzt: ["Immobilität", "Dekubitus Grad 2"], massnahmen: ["Lagerung", "Wärmeerhalt"],
      trupp: "T3", befund: "Weiblich, 90, Verlegung aus der Pflegeeinrichtung an der Klinikumszufahrt — gelb, KTW." },
    { id: 19, t: 1108, ll: [51.50200, 11.94060], kat: "SK3", sex: "m", alter: 77, geh: true, wach: true, atemweg: true,
      vit: { af: 16, puls: 84, spo2: 97, gcs: 15 },
      verletzt: ["Demenz — Orientierungsstörung"], massnahmen: ["Begleitung", "Registrierung"],
      trupp: "T4", befund: "Männlich, 77, Verlegung, desorientiert, sucht seine Frau — grün, Begleitperson zugeteilt." },
    { id: 20, t: 1196, ll: [51.50320, 11.94780], kat: "SK1", sex: "m", alter: 33, geh: false, wach: false, atemweg: true,
      vit: { af: 28, puls: 136, spo2: 85, rrs: 88, gcs: 8 },
      verletzt: ["SHT nach Böschungsabbruch", "Beckenprellung"], massnahmen: ["Sauerstoff", "HWS-Immobilisation", "Wärmeerhalt"],
      trupp: "T2", befund: "Helfer, 33, vom abrutschenden Uferweg mitgerissen, GCS 8 — rot, Schockraum voranmelden." },
    { id: 21, t: 1288, ll: [51.50600, 11.94340], kat: "SK3", sex: "w", alter: 24, geh: true, wach: true, atemweg: true,
      vit: { af: 17, puls: 88, spo2: 99, gcs: 15 },
      verletzt: ["Blasen an den Händen"], massnahmen: ["Verband"],
      trupp: "T1", befund: "Helferin, 24, Blasen vom Sandsackschleppen — grün, Ablösung empfohlen." },
    { id: 22, t: 1390, ll: [51.50260, 11.94640], kat: "SK2", sex: "m", alter: 66, geh: false, wach: true, atemweg: true,
      vit: { af: 21, puls: 102, spo2: 94, rrs: 150, gcs: 15 },
      verletzt: ["COPD-Exazerbation", "Sauerstoffgerät ohne Strom"], massnahmen: ["Sauerstoff", "Inhalation"],
      trupp: "T3", befund: "Männlich, 66, Heimsauerstoff seit der Abschaltung ohne Funktion — gelb, Transport mit O₂." },
    { id: 23, t: 1500, ll: [51.50480, 11.94920], kat: "SK3", sex: "m", alter: 41, geh: true, wach: true, atemweg: true,
      vit: { af: 16, puls: 82, spo2: 98, gcs: 15 },
      verletzt: ["Prellung Schulter"], massnahmen: [],
      trupp: "T1", befund: "Männlich, 41, gegen Absperrung gelaufen, Schulterprellung — grün." },
    { id: 24, t: 1620, ll: [51.50360, 11.94520], kat: "SK1", sex: "w", alter: 59, geh: false, wach: false, atemweg: false,
      vit: { af: 10, puls: 44, spo2: 74, gcs: 3, temp: 30.6 },
      verletzt: ["schwerste Unterkühlung 30,6 °C", "Bradykardie"], massnahmen: ["Beatmung", "Wärmeerhalt", "keine Bewegungsreize"],
      trupp: "BOOT1", befund: "Weiblich, 59, spät aus dem Obergeschoss geborgen, 30,6 °C, Bradykardie — rot, Ferntransport ECMO." },
  ];

  const funk = [
    { t: 0, von: "Leitstelle Halle", text: "Hochwasser Meldestufe 4 für die Saale. Einsatzstichwort Wassergefahr groß, Kröllwitz Uferzone. Krisenstab der Stadt tagt ab 06:00." },
    { t: 10, von: "Florian Halle 1/46", text: "Erstmeldung Uferweg West: Wasser steht 40 cm über der Deichkrone der Behelfslinie, Quellkade auf 30 m Länge. Nachforderung THW Fachberater Deich und Sandsacklogistik." },
    { t: 30, von: "ÖEL Radtke", text: "Einsatzabschnitte gebildet: EA 1 Deichverteidigung, EA 2 Evakuierung, EA 3 Wasserrettung, EA 4 Med, EA 5 Betreuung, EA 6 Transport. ELW 2 an der Talstraße in Betrieb." },
    { t: 66, von: "Rettungstrupp 1", text: "Patient 1 aus dem Rückstauwasser geborgen, 34,6 °C, gelb. Wärmeerhalt läuft, Transport zur Patientenablage.", refs: [1] },
    { t: 104, von: "THW Halle — Zugtrupp", text: "Auflastfilter über der Quellkade steht. Kontrollgänge alle zehn Minuten, landseitiger Deichfuß bleibt gesperrt." },
    { t: 148, von: "DLRG Bezirk Halle", text: "Bootseinsatzstelle Talstraße in Betrieb. Zwei Mehrzweckboote und ein Rettungsboot im Wasser, Funk auf Kanal Wasser." },
    { t: 214, von: "EA 2 Evakuierung", text: "58 Haushalte in der Uferzone, davon 12 mit Pflegebedarf. Zwei Heimbeatmungs- und ein Dialysepatient bekannt — Vorrang." },
    { t: 300, von: "Netzbetreiber", text: "Ortsnetzstation Am Zollrain ist freigeschaltet. Rund 340 Haushalte ohne Strom. Heimsauerstoff- und Dialysepatienten bitte vorziehen." },
    { t: 402, von: "THW — FGr Wassergefahren", text: "Person aus der Strömung geborgen — Beinaheertrinken, stark unterkühlt, GCS 5. NEF an die Bootseinsatzstelle.", refs: [9] },
    { t: 480, von: "LNA Dr. Seifert", text: "Sichtung in der Patientenablage läuft. Schwerpunkt Unterkühlung und internistische Zwischenfälle, weniger Trauma. Aufwärmzone im Behandlungsplatz erweitert." },
    { t: 664, von: "FW Halle Gefahrgut", text: "Heizöltank in der Uferzone aufgeschwommen und abgerissen. Ölfilm auf dem Rückstauwasser, Ölsperre wird gesetzt. Keller nicht betreten." },
    { t: 820, von: "EA 6 Transport", text: "Erster Ferntransport per Christoph 84 ab Behandlungsplatz — Ziel Universitätsklinikum Leipzig, ECMO-Zentrum ist voranmeldet.", refs: [9] },
    { t: 906, von: "Hochwasserzentrale", text: "Pegel Halle-Trotha hat den Scheitel erreicht. Rückgang langsam, Deichlinie bleibt über Nacht besetzt." },
    { t: 1026, von: "Drohne EA Aufklärung", text: "Böschungsabbruch am Uferweg Süd auf 25 m Länge. Kräfte sind zurückgenommen, Bereich gesperrt." },
    { t: 1090, von: "ÖEL Radtke", text: "Zufahrt zum Klinikum droht zu überspülen. Abschnitt Verlegung eingerichtet, 14 immobile Patienten aus zwei Pflegeeinrichtungen werden vorsorglich verlegt." },
    { t: 1340, von: "Gesundheitsamt", text: "Abwasserrückstau in tiefliegenden Kellern. Abkochgebot für die Uferzone wird vorbereitet, Merkblätter über die Betreuungsstelle." },
    { t: 1560, von: "ÖEL Radtke", text: "Zwischenmeldung an den Krisenstab: Deichlinie hält, 71 Personen evakuiert, 24 Betroffene medizinisch versorgt. Ablösung der Deichwachen ab 14:00 eingeplant." },
  ];

  return {
    id: "halle",
    kurz: "Halle (Saale) · Hochwasser Kröllwitz",
    sitzung: "Halle · Kröllwitz",
    geo: window.HAL_GEO,
    raster: { spalten: 14, zeilen: 11 },   // ~158 x 162 m je Feld
    absperrung: 400,
    rollen: {
      ablagen: ["PA", "PA2"], behandlungen: ["BHP"], betreuung: "BST",
      bereitstellung: "BR", halteplatz: "RMHP", verstorbene: "VER",
      landeplatz: "BHP",                        // Landung auf dem Sportplatz am BHP
      schaden: ["DEICH", "EVAK", "WR", "EVAK2"],  // hier wird gerettet und evakuiert
    },
    einsatz: {
      name: "Halle (Saale) · Kröllwitz — Hochwasser Saale, Deichverteidigung und Evakuierung",
      stichwort: "Wassergefahr groß / MANV 20 — Meldestufe 4",
      ort: "Uferweg West / Talstraße, Kröllwitz, 06120 Halle (Saale)",
      oel: "BF Halle, Radtke",
      lna: "Dr. Seifert",
      orgl: "Wendt",
      alarmiert: "05:40",
      betroffene: "ca. 70 evakuiert, 24 medizinisch versorgt",
      wetter: "4 °C, Dauerregen, Wind 280° 24 km/h, Sicht 3 km",
    },
    epi: EPI,
    abschnitte, gefahren, sperren, poi, kliniken, mittel, patienten, funk,
  };
})());
